"""Add CaseGraph

Revision ID: 009bc7874b40
Revises: 10594280db23
Create Date: 2026-06-15 10:49:00.609348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009bc7874b40'
down_revision = '10594280db23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_graphs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('graph_type', sa.String(length=50), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_graphs')
    # ### end Alembic commands ###
