"""Add digital_signatures and sio_actions tables

Revision ID: 847adee08adc
Revises: 83ebb48e4a53
Create Date: 2026-06-30 16:08:14.481940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '847adee08adc'
down_revision = '83ebb48e4a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('signed_by', sa.String(length=36), nullable=False),
    sa.Column('signer_role', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('ipc_sections', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('signature_hash', sa.String(length=64), nullable=False),
    sa.Column('suspicion_score_at_signing', sa.Float(), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature_hash')
    )
    op.create_table('sio_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('signature_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('ipc_sections', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('submission_authority', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notified_io', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signature_id'], ['digital_signatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sio_actions')
    op.drop_table('digital_signatures')
    # ### end Alembic commands ###
