"""add_is_primary_to_statements

Revision ID: ff861b0f538b
Revises: 56d883577ab9
Create Date: 2026-07-04 12:21:28.379500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff861b0f538b'
down_revision = '56d883577ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    op.execute("""
        UPDATE statements
        SET is_primary = true
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id, ROW_NUMBER() OVER(PARTITION BY case_id ORDER BY created_at ASC, id ASC) as rn
                FROM statements
            ) sub
            WHERE rn = 1
        )
    """)
    
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.alter_column('is_primary', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
